name: Upload IPA to TestFlight

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-latest

    steps:
      - name: Checkout repo (with LFS)
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          lfs: true

      - name: Upload IPA to TestFlight
        env:
          APPLE_ID:        ${{ secrets.APPLE_ID }}
          APP_SPECIFIC_PW: ${{ secrets.APP_SPECIFIC_PW }}
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file PocketCasebook.ipa \
            --username "$APPLE_ID" \
            --password "$APP_SPECIFIC_PW" \
            --verbose
